# Generated by Django 4.2.2 on 2023-08-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=255, null=True)),
                ('correoelectronico', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(null=True)),
                ('codigo_socio', models.CharField(max_length=10, null=True)),
                ('joined_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MisCursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_corto', models.CharField(choices=[('corto', '01'), ('dos', '02'), ('prime', '03')], default='corto', max_length=50)),
                ('nombre_curso', models.CharField(max_length=100, null=True)),
                ('numeral_curso', models.CharField(max_length=100, null=True)),
                ('url_curso', models.CharField(max_length=100, null=True)),
                ('url_producto', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MisDatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100, null=True)),
                ('codigo', models.CharField(max_length=10, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('fecha', models.DateField(null=True)),
                ('filial', models.CharField(choices=[('ah', 'Ahuachapán'), ('so', 'Sonsonate'), ('sa', 'Santa Ana'), ('ll', 'La Libertad'), ('ch', 'Chalatenango'), ('ss', 'San Salvador'), ('cs', 'Cuscatlán'), ('lp', 'La Paz'), ('sv', 'San Vicente'), ('ca', 'Cabañas'), ('us', 'Usulután'), ('sm', 'San Miguel'), ('mo', 'Morazán'), ('lu', 'La Unión')], default='ss', max_length=50)),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('empresa', models.CharField(max_length=100, null=True)),
                ('registrado', models.CharField(max_length=2, null=True)),
                ('socio', models.CharField(max_length=2, null=True)),
                ('telefono', models.CharField(max_length=10, null=True)),
                ('trabaja', models.CharField(max_length=2, null=True)),
                ('usuario', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Socios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filial', models.CharField(max_length=100)),
                ('codigo_camarasal', models.CharField(max_length=10, null=True)),
                ('razon_social', models.CharField(max_length=80)),
                ('persona_natural', models.CharField(max_length=80, null=True)),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
    ]
